#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#    Listens on port 80.
#    Returns a page containing "Hello World" when queried
#    at the root with a curl GET request.
#    Configures /redirect_me as a "301 Moved Permanently".
#    Includes a custom 404 page containing "Ceci n'est pas une page".
#    Contains a custom HTTP header named X-Served-By.
#    The value of the HTTP header is the hostname of the running server.

# Update package list and install Nginx
apt-get update
apt-get install -y nginx

# Create web root and custom pages
mkdir -p /var/www/html
echo "Hello World" > /var/www/html/index.html
echo "JS" > /var/www/html/404.html

# Configure Nginx
cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    add_header X-Served-By \$hostname;

    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOL

# Restart Nginx to apply the configuration
systemctl restart nginx

